#!/usr/bin/env bash
#
# mpseek - conditional search queries for mpd

MPD_FIELDS="file name artist album albumartist comment composer date genre performer title"

join_by() {
    local IFS="$1"; shift; echo "$*";
}

array_index() {
    local seeking=$1; shift
    local idx=0
    for opt; do
        ((idx++))
        if [[ $opt == "$seeking" ]]; then
            echo $idx
            break
        fi
    done
    false
}

fulltext_func() {
    local arg="$1"; shift
    if (( $# )); then
        awk -v IGNORECASE=1 "/$arg/" | fulltext_func "$@"
    else
        awk -v IGNORECASE=1 "/$arg/"
    fi
}

filter() {
    local query condition format

    declare -a fields=(${MPD_FIELDS[@]})
    declare -a format_fields=()
    for field in "${fields[@]}"; do
        format_fields+=("%${field}%")
    done
    format=$(join_by "^" "${format_fields[@]}")

    query="$*"
    IFS=$'\n' queries=($(xargs -n1 <<< "$query"))
    local key idx value
    declare -a fulltext=()
    for q in "${queries[@]}"; do
        if [[ "$q" =~ "&&" ]] || [[ "$q" == "||" ]] ||\
            [[ "$q" == "(" ]] || [[ "$q" == ")" ]]; then
            condition+=" $q "
        elif [[ "$q" =~ [a-z]+= ]]; then
            key="${q%%=*}"
            idx=$(array_index "$key" "${fields[@]}")
            (( idx )) || break
            value="${q##*=}"
            value=${value//=/==}
            condition+="tolower(\$${idx})==\"${value,,}\""
        elif [[ "$q" =~ [a-z]+~ ]]; then
            key="${q%%~*}"
            idx=$(array_index "$key" "${fields[@]}")
            (( idx )) || break
            value="${q##*~}"
            condition+="tolower(\$${idx})~/${value,,}/"
        elif [[ "$q" =~ [a-z]+\< ]]; then
            key="${q%%<*}"
            idx=$(array_index "$key" "${fields[@]}")
            (( idx )) || break
            value="${q##*<}"
        elif [[ "$q" =~ [a-z]+\> ]]; then
            key="${q%%>*}"
            idx=$(array_index "$key" "${fields[@]}")
            (( idx )) || break
            value="${q##*>}"
            condition+="\$${idx}>${value}"
        else
            fulltext+=("$q")
        fi
    done

    (( ${#condition} || ${#fulltext[@]} )) && \
        mpc listall --format "$format" |\
            awk -F"^" "${condition:-1}" 2>&- |\
            fulltext_func "${fulltext[@]}" |\
            awk -F"^" '{print $1}'
}

filter "$@"
